### PR TITLE
Caching

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by roidelapluie** [comment]
Please note that caching is not persisted to disk yet.

**Comment by roidelapluie** [comment]
and maybe --no-cache

**Comment by attachmentgenie** [comment]
all 3 seem important, if you run in offline that delete and refresh are very interesting/needed. the no-cache is to say run in online mode

**Comment by roidelapluie** [comment]
Contracts and projects don't change a lot ; it does not make sense to query them each time we need them

**Pull request merged**
